name: CMake Build & Clang Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Old CMake Cache & Build Folder
        run: |
          rm -rf ${{ github.workspace }}/build  # Ensure a clean build directory
          mkdir -p ${{ github.workspace }}/build

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y cmake g++ make clang-format libgtk-3-dev  # Install necessary packages

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build Project
        run: |
          cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Run Tests (Optional)
        run: |
          cd ${{ github.workspace }}/build
          ctest --output-on-failure || echo "Some tests failed, but workflow continues..."

  clang-format:
    name: Clang Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Verify .clang-format exists
        run: |
          if [ ! -f .clang-format ]; then
            echo "Error: .clang-format file not found in repository root"
            exit 1
          fi

      - name: Check formatting
        run: |
          FORMATTING_ISSUES=0
          for file in $(find . -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \)); do
            echo "Checking $file..."
            clang-format -style=file "$file" | diff "$file" -
            if [ $? -ne 0 ]; then
              FORMATTING_ISSUES=1
              echo "::error::Formatting issues found in $file"
            fi
          done

          if [ $FORMATTING_ISSUES -ne 0 ]; then
            echo "Formatting check failed. Please run clang-format locally and commit the changes."
            exit 1
          else
            echo "All files are properly formatted."
          fi
